server:
  port: 8092    
spring:     #定义springmvc视图解析器
  mvc:    view:      prefix: /WEB-INF/views/
      suffix: .jsp

logging:
  config: classpath:logging-config.xml
  level: 
    com.jt.mapper: debug 

dubbo:
  scan:
    basePackages: com.jt
  application:
    name: consumer-web   #定义消费者名称
  registry:               #注册中心地址
    address: zookeeper://192.168.126.186:2181?backup=192.168.126.186:2182,192.168.126.186:2183    
    
    
    
    
    
    
    
    
         
        